# H2 in-memory database configuration for tests
db.default.driver = org.h2.Driver
db.default.url = "jdbc:h2:mem:play;DB_CLOSE_DELAY=-1;MODE=MySQL"
db.default.username = "sa"
db.default.password = ""
db.default.dialect = org.hibernate.dialect.H2Dialect

# Hibernate settings
jpa.default = defaultPersistenceUnit
jpa.default.dialect = org.hibernate.dialect.H2Dialect
jpa.default.hbm2ddl.auto = create-drop  # delete everythinh after test
